### ISSUE TITLE
Command line option to enable and disable OverlayFS 

### ISSUE THREAD

**Issue by mangelozzi** [RPi-Distro/raspi-config#182]
To automate updates, its necessary to be able to be able to disable and enable overflayFS from the command line. I read many posts of people struggling with it, but I am not winning with hacking this script myself. I think many people would benefit from command line flags to be able to do this.

Refer to this post <https://forums.raspberrypi.com/viewtopic.php?t=279530>

Unfortunately the line numbers have changes, its not too helpful.

```
sudo raspi-config --enable-overlayfs
sudo raspi-config --disable-overlayfs
```

Is there any information on how to use the script? None of these work:
```
man raspi-config
raspi-config --help
raspi-config --h
```

I have tried all sorts of ways to source the script and call the enable/disable overflayfs functions and none of it works. Some documented help and command line switches would be really awesome!

**Comment by bensonrodney** [comment]
Can't you already do this?
`sudo raspi-config nonint do_overlayfs 0`
(0 to enable, 1 to disable)

**Comment by XECDesign** [comment]
raspi-config is intended to be a TUI not a CLI application. `nonint` exists so that our other applications can call functions from raspi-config. Then if there's an issue, we can fix it in one place rather than across multiple packages. It's not documented because it's not something that the average user is expected to use.
