### ISSUE TITLE
raspi-config illegal instruction and it not work

### ISSUE THREAD

**Issue by shigerusz** [RPi-Distro/raspi-config#211]
Hello,

When I run "sudo raspi-config", it shows blue windows and "illegal instruction" below:

![raspi-config_illegal_instruction](https://user-images.githubusercontent.com/35642514/216494916-537af972-d01e-4429-b7c9-659768b08669.png)

I did what I could do:
apt reinstall raspi-config, tried original PI-OS, dpkg -V (verify), search trouble for the hint but I got out of hand.

Please help me.

my system information is below:

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
pi@raspberrypi:~ $ sudo apt list raspi-config
一覧表示... 完了
raspi-config/stable,stable,now 20221214 all [インストール済み]

**Comment by XECDesign** [comment]
`raspi-config` just runs other things, so if you're seeing `illegal instruction`, then it's likely one of those things it runs is corrupted.

A starting point might be adding `-x` to the script's shebang to see where it's going wrong and if that doesn't help then `strace` with the `-f` option should help track it down.

Closing since this isn't a `raspi-config` issue. I would recommend asking on the forum.
