### ISSUE TITLE
Add man page

### ISSUE THREAD

**Issue by AdriaanDeVos** [RPi-Distro/raspi-config#94]
Documentation on how to use raspi-config should be available in a manual page.

**Comment by XECDesign** [comment]
It would be nice, but I haven't seen anybody stumble in basic use of the tool. Some options may be unclear, but that's probably better addressed within raspi-config itself. If somebody wants to write and maintain a man page and it meets basic standards, then I'll merge the PR. Otherwise, I don't think it's useful enough to justify the time spent.
